### ISSUE TITLE
notepad++ plugin manager is not working

### ISSUE THREAD

**Issue by adamtonybulchak** [mmtrt/notepad-plus-plus#1]
the installation of notepad++ works.
the application of notepad++ works.
import of plugins works.
the plugin manager does not work.

Thanks for your work.
you can contact me at abulchak@gmail.com

**Comment by mmtrt** [comment]
This snap did not had network access so now it does have 1137ee5f3d6b8d8e90bed91fff844b8c6c24f06a

Version `7.5.6 (37)` have network access now released on stable.

Make sure you have checked the two boxes on Plugin manager settings in order to make it work.
* Show unstable plugins
* Force `HTTP` instead of `HTTPS` for downloading Plugin List.
