### ISSUE TITLE
Can't display the hidden folder and file in $HOME 

### ISSUE THREAD

**Issue by studyit** [mmtrt/notepad-plus-plus#31]
I need edit the configuration files in .config folder using newest version of notepad-plus-plus,  butI can't read the hidden files.
how to solve it ?

**Comment by mmtrt** [comment]
Due to limitation of snap strict confinement without granted permissions snap can not access such directories or files. So either snap has to be classic or with devmode confinement to access such files.

Anyways I've pushed devmode snap to beta branch which won't be updated.

`snap refresh --beta --devmode notepad-plus-plus`
