### ISSUE TITLE
update

### ISSUE THREAD

**Issue by huezo** [mmtrt/notepad-plus-plus#32]
![NCUhTZj](https://user-images.githubusercontent.com/15940634/151228672-78af8139-d9b8-468b-917e-ab6c85b2653b.png)

**Comment by AdrianSthlm** [comment]
It was updated today for me with the latest version 8.4.4 through SNAP/Ubuntu Software. The problem is that the whole computer lags down to zero CPU and basically nothing works. Uninstalling Notepad++ from SNAP solves the problems. Can someone take a look at this? I wish to have a fix or being able to install an older version, such as 8.4.3. That version worked fine. Any ideas of how to get the old version?
